### PR TITLE
Added initial View Model 

### PR DESCRIPTION
**Pull request by AB261**
View Model is part of the android architecture to make the fragments more lean. It is the middle man that stores all the information. This is the first step in developing the viewmodel. In the next phase majority of the code in the fragment will be moved to the viewmodel. 
Deals with Issue #36 and #32

### CODE REVIEW

**Comment by jupancs** [comment]
Did you add any dependencies into Gradle for ViewModel? I have a problem importing package about ViewModel, I didn't see any libraries regarding the ViewModel in Gradle settings. Let me know if I missed anything.

**Comment by AB261** [comment]
> Did you add any dependencies into Gradle for ViewModel? I have a problem importing package about ViewModel, I didn't see any libraries regarding the ViewModel in Gradle settings. Let me know if I missed anything.

I think I forgot to add the library while committing but the recent commit has the changed build.gradle with the dependency added. I still need to connect the viewmodel with the repo but the majority of the fragment is refactored. 
Reference Issue #36, #32

**Comment by jupancs** [comment]
The pull request works. 
I know I did a really bad job on commenting, but can I ask you to add some necessary comments for the code? Btw, as for the coding style, would you mind referring to [https://google.github.io/styleguide/javaguide.html](url). No need to strictly follow the style, but make sure you have a consistent style. :)

**Comment by AB261** [comment]
> [https://google.github.io/styleguide/javaguide.html](url).

Sounds good

**Pull request merged**
